### ISSUE TITLE
[Feature Request] New Command → Open Plugins Settings from a Modal

### ISSUE THREAD

**Issue by FelipeRearden** [Lisandra-dev/obsidian-open-settings#1]
Hello @Lisandra-dev !!!!!!

Thank you very much for this  plugin !!!! I have been doing this manually an it's amazing to have a plugin to do this for me :)

My FR is about a new command to add an additional way to open the settings of a plugin. 

## My FR

It is a new command from Command Palette that will open a Modal with all active plugins

After Selecting a Plugin from Modal, it will open the Setting of the selected Plugin. 

## Why I Need This Feature

I am gonna use a simple example to explain...

Image that I have 20 plugins active in my vault.

From these 20, I created plugin settings commands using this plugin for 5 plugins that I used the settings frequently.

To access the commands from these 5 plugins I created a QuickAdd Modal. 

![ED793BE0-F2D8-4E30-A5C9-8C47DE68B892](https://github.com/Lisandra-dev/open-plugin-settings-commands/assets/85180696/ce6c1c62-e047-4d11-83c1-cb8a68ac5496)

What about the 15 pluigns, how do I access there Settings ?

→ This is My FR: A new command that will open a Modal with all plugins for me to select a plugin to open the Settings. 

→ This way, I can create a 6th entry in My QuickAdd Modal to easily open the settings from these pluigns that I almost dont open the settings. 

![FCC6FC1E-E3A9-47A2-830F-6760B46BBBDA](https://github.com/Lisandra-dev/open-plugin-settings-commands/assets/85180696/77f52309-9984-4c29-b070-b84a7f37aeb8)

That will open a Modal that is similar to the modal that you have in Settings `Add a new plugin`. Instead of registering a new setting command, it will open the setting window from the selected plugin.

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by Mara-Li** [comment]
Hey! This command exists on Hotkey Helper, if you use it!
I can add it, anyway :)

**Comment by FelipeRearden** [comment]
Hello @Lisandra-dev !!!!

Thank you very much for the quick reply !!!!

> Hey! This command exists on Hotkey Helper, if you use it!

I didn't know about that. To be honest I never installed Hotkey Helper because I think it has features that dont fit my workflow :) 

> I can add it, anyway :) 

Would be amazing if you could do that 🙏 but feel free to decide what to do :) 

In my humble opinion, would be a great addition to this plugin, I dont know that prefect word in English, but would be a like if a puzzle is 100% complete :)

Let me know what you think :)

Have a great day ☀️

**Comment by Mara-Li** [comment]
Done ! It was pretty easy as everything already exists ^^
The command is named "Open other settings" :)

**Comment by FelipeRearden** [comment]
> Done ! It was pretty easy as everything already exists ^^
> The command is named "Open other settings" :)

Thank you very much @Lisandra-dev !!!!!!!! 🎉🎉🎉🎉

It is working perfect, thank you very much !!!!

I really like that the modal is filtered by plugins that already has a command . Smart idea 💙

--- 

Thank you very much for your help and I wish you a fantastic day ☀️
