### ISSUE TITLE
[FR]: feature to rename commands (useful in native command palette→pinned commands workflow)

### ISSUE THREAD

**Issue by maggaou** [Lisandra-dev/obsidian-open-settings#2]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Is your feature related to a problem ?

-

### What solution do you want to see ?

Hi. As mentioned in #1 QuickAdd among other community plugins could be used to create a custom action (launched by a keyboard shortcut etc) to display a customized lists of commands that could be selected using mouse or keyboard. However what if that customization is not desired by the user for example because of the desire for simplicity and using only the native command palette **with pinned commands**.

I'm not saying that the user in #1 doesn't make use of the native command palette (or some other equivalent plugin), but he is definitely introducing one additional keyboard shortcut for his workflow (new keyboard shortcut for his customized list of commands) OR alternatively he replaces the keyboard shortcut for the command palette and includes it as one of his commands in the customized command list. In either way he adds more complexity to his workflow because executing his commands are scattered to two different places—his customized commands list and the command palette itself. On the other hand using only command palette to execute commands would make running commands very straightforward, peaceful and simple. For the customization to the native command palette itself, one could customize the names appeared in pinned commands (not possible yet natively using CSS etc). There are at least four community plugins offering extended customization for the command palette either impementing their own command palette or modifying the existing command palette:

1. [Command Alias](https://github.com/yajamon/obsidian-command-alias-plugin). This is the most powerful plugin in my list here, although the current implementation doesn't include custom appearance when commands appear in the command palette — these custom aliases look really awful when they appear in the command palette.
2. [Better Command Palette](https://github.com/AlexBieg/obsidian-better-command-palette). Currently it doesn't offer any appearance customization for pinned commands — however it uses its own style for every command.
3. [QuickSwitcher++](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#run-commands). It doesn't offer any appearance customization to commands but it adds or changes command palette's functionality similar to Better Command Palette which is focused on functionality of the command palette.
4. [Command Palette--](https://github.com/qawatake/obsidian-command-palette-minus-plugin). This is simple plugin to hide commands from the command palette. Better Command Palette implements the same feature.

In theory Better Command Palette could implement new features concerning about custom command appearance OR Obsidian could introduce [CSS variables](https://docs.obsidian.md/Reference/CSS+variables/CSS+variables) to target individual pinned commands in the command palette or general commands appearance. In either case I propose small customization feature to Open plugin settings: customize commands names so for example emojis could be used for customization for pinned commands in the command palette. However in general Command Alias will be very powerful plugin and Obsidian could later offer better support for Command Alias+Better Command Palette combination so that command appearance could be customized. 

### Obsidian information

```bash session
------------------
```

### Plugin version

-----------

**Comment by Lisandra-dev** [comment]
I don't understand what do you want.
