### ISSUE TITLE
[FR]: Add support for core plugins (mainly Daily notes)

### ISSUE THREAD

**Issue by maggaou** [Lisandra-dev/obsidian-open-settings#3]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### What solution do you want to see ?

Hi and thanks for the latest addition #2 — sorry I was careless to include too much thoughts for only self. Obviously it was wrong place to generate general discussion about new features in Obsidian, I'm sorry about that.

## About this feature request
Currently the plugin offers support for only community plugins. Some core plugins like Daily notes offer useful configuration (template file location) which could be accessed in more streamlined way to support Daily notes workflows where different templates are used according to one's ongoing needs.

### Obsidian information

```bash session
---
```

### Plugin version

---

**Comment by Mara-Li** [comment]
No worry, I also forggot to check the first obvious thing : the title of the issue :')
I will check how to do that, but I don't think it's difficult!
